// src/constants/auditActions.ts
export const AUDIT_ACTIONS = {
  // User Actions
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USERS_DEACTIVATED_BULK: 'USERS_DEACTIVATED_BULK',
  USERS_REACTIVATED_BULK: 'USERS_REACTIVATED_BULK',
  USERS_ROLE_CHANGED_BULK: 'USERS_ROLE_CHANGED_BULK',

  // Media Category Actions
  MEDIA_CATEGORY_CREATED: 'MEDIA_CATEGORY_CREATED',
  MEDIA_CATEGORY_UPDATED: 'MEDIA_CATEGORY_UPDATED',
  MEDIA_CATEGORY_DELETED: 'MEDIA_CATEGORY_DELETED',

  // Media Tag Actions
  MEDIA_TAG_CREATED: 'MEDIA_TAG_CREATED',
  MEDIA_TAG_UPDATED: 'MEDIA_TAG_UPDATED',
  MEDIA_TAG_DELETED: 'MEDIA_TAG_DELETED',

  // Media Actions
  MEDIA_UPLOADED: 'MEDIA_UPLOADED',
  MEDIA_UPDATED: 'MEDIA_UPDATED',
  MEDIA_DELETED: 'MEDIA_DELETED',
  MEDIA_DELETED_BULK: 'MEDIA_DELETED_BULK',

  // Role Actions
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
